### ISSUE TITLE
Large file upload fails (without any feedback of the failure to the user)

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2406]
On production, a file upload (file size was 1.5MB) failed and the user was not informed that the upload failed. The issue can be reproduced by attempting to upload a large file.

**Comment by teodorescuserban** [comment]
Fixed.
The issue was related with the Friday's migration.

The error message found was `413 Request Entity Too Large`
There was an additional "blank" nginx put in front of our nginx that had only the default `client_max_body_size` param.

After I added `client_max_body_size 1G;` it worked.

**Comment by reubano** [comment]
Issue still present on test server when posting to `api/action/resource_create`

**Comment by reubano** [comment]
Also when updating a resource with a file >1MB using the website, it just hangs.

**Comment by teodorescuserban** [comment]
Feel free to reopen this.

Please check the debug tools (see if the POST to upload_handle returns anything other than status_code 200) and paste here the output (or alternatively send me the file you want to upload).
