### ISSUE TITLE
Links: open new tab not working very well

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2942]
Production > Go to Home page, click on "Data" or "Browse" - it will open a new tab.
@mbellotti I think the javascript way of doing this is not great as it has collateral actions. 
We will have to hotfix this one

**Comment by mbellotti** [comment]
Yup, this is a minor problem with site_url and HTTPS. I fixed it six days
ago, but no one has merged the PR.

**Comment by danmihaila** [comment]
this is merged, but now https://github.com/OCHA-DAP/hdx-ckan/issues/2882 is still an issue
